# Generated by Django 4.2 on 2025-07-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cName", models.CharField(max_length=50, unique=True)),
                ("cEmail", models.EmailField(max_length=254)),
                ("cLogo", models.ImageField(blank=True, upload_to="images")),
                ("cUrl", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eFname", models.CharField(max_length=50)),
                ("eLname", models.CharField(max_length=50)),
                ("eEmail", models.EmailField(max_length=254)),
                ("ePhone", models.CharField(max_length=50)),
                (
                    "eCompany",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mirai.company"
                    ),
                ),
            ],
            options={
                "db_table": "employee",
            },
        ),
    ]
